name: Fly Deploy

on:
  push:
    paths:
      - "api/**"
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy ./api --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_TOKEN }}
